import React, {Component} from "react";

export class InfoPanel extends Component {


    render() {
        return (
            <div className="infoPanel">
                <p>Font generated by <a href="http://www.flaticon.com">flaticon.com</a>.</p>
                <p>Under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noopener noreferrer">CC</a>: <a data-file="satellite-2"
                                                                                          href="http://www.freepik.com" target="_blank" rel="noopener noreferrer">Freepik</a>
                </p>
            </div>
        )
    }
}

export default InfoPanel;
