import React, {Component} from "react";

export class InfoPanel extends Component {


    render() {
        return (
            <div className="infoPanel">
                <p>This website is a simple tool to search through the <a href="https://exoplanetarchive.ipac.caltech.edu/" target="_blank" rel="noopener noreferrer">NASA Exoplanet Archive</a> | The planet images use a font generated by <a href="http://www.flaticon.com" target="_blank" rel="noopener noreferrer">flaticon.com</a>. Under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noopener noreferrer">CC</a>: <a data-file="satellite-2"
                                                                                          href="http://www.freepik.com" target="_blank" rel="noopener noreferrer">Freepik</a>. | 	&copy; 2018 by <a href="https://github.com/ldrobnik/" target="_blank" rel="noopener noreferrer">Łukasz Drobnik</a>
                </p>
            </div>
        )
    }
}

export default InfoPanel;
